config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  resources :books, only: [:create, :index]

  get 'books/new'

  get 'books/:id' => 'books#show', as:'book'
  get 'books/:id/edit' => 'books#edit', as:'edit_book'
  patch 'books/:id/edit' => 'books#update', as:'update_book'
  delete 'books/:id' => 'books#destroy', as:'destroy_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      @books = Book.all
      render :index
    end
  end
  
  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'Book was successfully updated.'
    else
      render :edit
    end
    
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1 class="headline">Editing Book</h1>
<div class="show">
<% if @book.errors.any? %>
  <div class="error">
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>


<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
<div class="box">
<p>Title</p>
<%= f.text_field :title %>
</div>

<div class="box">
<p>Body</p>
<%= f.text_area :body %>
</div>

<div class="box">
<p><%= f.submit 'Update Book' %></p>
</div>

<p>
<%= link_to "Show",book_path(@book.id) %>
 | 
<%= link_to "Back",books_path %>
</p>

<% end %>
</div>

app/views/books/index.html.erb
<p class="flash"><%= notice %></p>
<h1 class="headline">Books</h1>

<table class="table">
    <thead>
      <tr>
        <th><strong>Title</strong></th>
        <th><strong>Body</strong></th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td class="tbody title"><%= book.title %></td>
        <td class="tbody body"><%= book.body %></td>
        <td class="tbody"><%= link_to "Show", book_path(book.id) %></td>
        <td class="tbody"><%= link_to "Edit", edit_book_path(book.id) %></td>
        <td class="tbody"><%= link_to "Destroy", destroy_book_path(book.id),method: :delete, "data-confirm" => "Are you sure？" %></td>
      </tr>
      <% end %>
    </tbody>
</table>

<h2 class="headline2">New book</h2>

<% if @book.errors.any? %>
  <div class="error">
  <p><%= @book.errors.count %>errors prohibited this book from being saved:</p>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>



<div class="new">
<%= form_with model: @book do|f| %>
  <div class="box">
  <p>Title</p>
  <%= f.text_field :title %>
  </div>

	<div class="box">
  <p>Body</p>
  <%= f.text_area :body %>
  </div>

	<div class="box">
  <p><%= f.submit 'Create Book' %></p>
  </div>
<% end %>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: '/books', method: :post do|f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Body</h4>
  <%= f.text_area :body %>
	
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<!--<h2>タイトル</h2>-->
<div class = "show">


<p class="flash"><%= notice %></p>

<p class = "show2">
    <span><strong>Title: </strong></span>
    <span><%= @book.title %></span>
</p>

<p class = "show2">
    <span><strong>Body: </strong></span>
    <span><%= @book.body %></span>
</p>


<%= link_to "Edit", edit_book_path(@book.id) %>
 |
<%= link_to "Back",books_path %>

</div>

app/views/homes/top.html.erb
<h1 class="headline">
    ようこそ <strong>Bookers</strong> へ！
</h1>

<p class="intro">
    <strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や
</p>
<p class="intro">
    印象を共有し交換することができます
</p>
<p class="intro">
    <%= link_to "start",books_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>